import { AdditiveBlending, NormalBlending } from 'three';
import { Model } from './type';

const INITIAL_PARAMETERS: Model = {
  particleCount: 100,
  particleLife: 3,
  emitterLife: 10,
  flowMode: true,
  trail: false,
  repeat: true,

  boxSize: [0.3, 0.3, 0.3],
  centerVelocityBase: 0,
  centerVelocitySpread: 0,
  velocityBase: [0, 0, 0],
  velocitySpread: [0, 0, 0],
  accelerationBase: [0, 0, 0],
  accelerationSpread: [0, 0, 0],
  angle: 0,
  angleVelocityBase: 0,
  angleVelocitySpread: 0,
  sizes: [1, 1, 1],
  startColors: ['#000000'],
  endColors: ['#000000'],
  startOpacity: 1,
  endOpacity: 0,

  texture: 'smoke',
  blending: NormalBlending,
  depthComparison: false,
};

export const fountain: Model = {
  ...INITIAL_PARAMETERS,
  texture: 'star',
  boxSize: [0.3, 0.3, 0.3],
  flowMode: true,
  particleCount: 100,
  particleLife: 3,
  emitterLife: 10,
  velocityBase: [0, 6, 0],
  velocitySpread: [4, 1, 4],
  accelerationBase: [0, -2, 0],
  angleVelocitySpread: 360,
  sizes: [0.1, 1, 1.2],
  startOpacity: 0.8,
  endOpacity: 0.4,
  startColors: [
    '#ff0000',
    '#ff7f00',
    '#ffff00',
    '#00ff00',
    '#0000ff',
    '#4b0082',
    '#8b00ff',
  ],
  endColors: [
    '#ffcccc',
    '#ffe5cc',
    '#ffffcc',
    '#ccffcc',
    '#ccccff',
    '#e0ccff',
    '#f2ccff',
  ],
};

export const fire: Model = {
  ...INITIAL_PARAMETERS,
  texture: 'fire',
  boxSize: [0.1, 0.1, 0.1],
  particleCount: 100,
  particleLife: 2,
  repeat: false,
  velocityBase: [0, 1, 0],
  velocitySpread: [0.1, 0, 0.1],
  accelerationBase: [0, -0.1, 0],
  angleVelocitySpread: 360,
  sizes: [0.5, 1.5, 0.5],
  startColors: ['#ffff80'],
  endColors: ['#ff8080'],
};

export const smoke: Model = {
  ...INITIAL_PARAMETERS,
  texture: 'smoke',
  boxSize: [0.1, 0.1, 0.1],
  flowMode: true,
  particleCount: 100,
  particleLife: 2,
  velocityBase: [0, 1, 0],
  velocitySpread: [0.3, 0.1, 0.3],
  accelerationBase: [-0.1, -0.2, -0.1],
  angleVelocitySpread: 90,
  sizes: [0.5, 1, 2],
  startColors: ['#333333'],
  endColors: ['#eeeeee'],
};

export const fog: Model = {
  ...INITIAL_PARAMETERS,
  texture: 'smoke',
  boxSize: [10, 4, 10],
  flowMode: false,
  particleCount: 50,
  particleLife: 5,
  emitterLife: 5,
  angle: 180,
  sizes: [70, 70, 70],
  startColors: ['#eeeeee'],
  endColors: ['#eeeeee'],
  startOpacity: 0.5,
  endOpacity: 0.5,
  blending: NormalBlending,
};

export const snow: Model = {
  ...INITIAL_PARAMETERS,
  texture: 'glow',
  boxSize: [6, 0.5, 6],
  flowMode: true,
  particleCount: 200,
  particleLife: 2,
  velocityBase: [0, -1, 0],
  velocitySpread: [1, 0.3, 1],
  accelerationBase: [0, -0.5, 0],
  angleVelocitySpread: 180,
  sizes: [0.3, 0.2, 0.2],
  endOpacity: 0.5,
  startColors: ['#ebe9e9'],
  endColors: ['#ebe9e9'],
};

export const firework: Model = {
  ...INITIAL_PARAMETERS,
  texture: 'circle',
  boxSize: [0.1, 0.1, 0.1],
  particleCount: 150,
  flowMode: false,
  particleLife: 3,
  emitterLife: 10,
  centerVelocityBase: 1,
  centerVelocitySpread: 0.2,
  velocityBase: [0, 0.5, 0],
  accelerationBase: [0, -0.5, 0],
  angleVelocitySpread: 60,
  sizes: [0.1, 0.5, 0.1],
  startColors: ['#0700cc', '#eb2a2a', '#ffd94d'],
  endColors: ['#cc0000', '#e8c6c6', '#fff099'],
  blending: AdditiveBlending,
  trail: true,
};

